# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-07-28 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livraria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='isbn',
            field=models.IntegerField(),
        ),
    ]
